Made FirstWeek
Dev-incubator/WebAutoparkArseniy pull request #1
Opened 2021-07-26 10:20 UTC by aces47

Add Entities of WebAutopark.
Made IRepository interface.
Made Repository classes for Vehicle, VehicleType and Detail

2021-07-26 14:51 UTC, kuzmiich requested changes
Const fields are usually named using PascalCase QueryGet...

2021-07-26 14:54 UTC, kuzmiich commented on DAL/Entities/Vehicle.cs
> +        private const int _taxBasicShift = 5;
Use PascalCasе

2021-07-27 10:19 UTC, PushMeNow requested changes

2021-07-27 10:19 UTC, PushMeNow commented on DAL/Entities/Vehicle.cs
> +        private const int _taxBasicShift = 5;
Agree, constants usually should be written by PascalCase.

2021-07-27 10:19 UTC, PushMeNow commented on DAL/Entities/Vehicle.cs
> +        public int Id { get; set; }
Usually we don't use name for identifier just 'Id' because it is pretty vague name: id for what? You have to give name for Id uniquely.

2021-07-27 10:19 UTC, PushMeNow commented on DAL/Interfaces/IRepository.cs
> +        void Delete(int id);
Why your Get methods are async but method for data manipulation are not?

2021-07-27 10:19 UTC, PushMeNow commented on DAL/Repositories/DetailRepository.cs
> +        public void Update(Detail item) => connection.ExecuteAsync(queryUpdate, item);
Never use 'void' keyword for async method it is obsolete and not stable approach.

2021-07-27 10:19 UTC, PushMeNow commented on DAL/Repositories/DetailRepository.cs
> +        public async Task<Detail> GetById(int id) => await connection.QueryFirstAsync<Detail>(queryGetById, id);
If you can return Task result you should not use async/await keywords.

2021-07-28 12:02 UTC, aces47 commented on DAL/Entities/Vehicle.cs
> +        private const int _taxBasicShift = 5;
Fixed

2021-07-28 12:02 UTC, aces47 commented on DAL/Entities/Vehicle.cs
> +        public int Id { get; set; }
Fixed

2021-07-28 12:02 UTC, aces47 commented on DAL/Interfaces/IRepository.cs
> +        void Delete(int id);
Fixed

2021-07-28 12:02 UTC, aces47 commented on DAL/Repositories/DetailRepository.cs
> +        public void Update(Detail item) => connection.ExecuteAsync(queryUpdate, item);
Fixed

2021-07-28 12:03 UTC, aces47 commented on DAL/Repositories/DetailRepository.cs
> +        public async Task<Detail> GetById(int id) => await connection.QueryFirstAsync<Detail>(queryGetById, id);
Fixed

2021-07-28 19:12 UTC, PushMeNow approved these changes

2021-07-31 14:15 UTC, kuzmiich approved these changes
Well done

2021-08-02 08:56 UTC, merged