Made Second week
Dev-incubator/WebAutoparkArseniy pull request #2
Opened 2021-07-31 09:42 UTC by aces47

Add all entities and repositories for them.
Add Repositories to DI.

2021-08-02 19:13 UTC, PushMeNow requested changes

2021-08-02 19:13 UTC, PushMeNow commented on WebAutopark/Startup.cs
> +            services.AddTransient<IRepository<Order>, OrderRepository>(provider => new OrderRepository(connectionString));
All these services must be scoped because there isn't seance to create it on each call of DI. Better create this service one per request.

2021-08-03 14:16 UTC, aces47 commented on WebAutopark/Startup.cs
> +            services.AddTransient<IRepository<Order>, OrderRepository>(provider => new OrderRepository(connectionString));
Fixed

2021-08-04 14:48 UTC, PushMeNow approved these changes

2021-08-04 15:05 UTC, kuzmiich approved these changes
Well done

2021-08-04 15:18 UTC, merged